//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class meetmeEntities : DbContext
    {
        public meetmeEntities()
            : base("name=meetmeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<ListedContacts> ListedContacts { get; set; }
    }
}
